import {MigrationInterface, QueryRunner} from "typeorm";

export class MockPosts1635935550253 implements MigrationInterface {

    public async up(_: QueryRunner): Promise<void> {
//         queryRunner.query(`
//         insert into post (title, text, "creatorId", "createdAt") values ('Children of the Corn V: Fields of Terror', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 1, '2021-08-27T23:52:25Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Arachnophobia', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 1, '2021-02-23T05:44:32Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Child, The', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 1, '2020-12-11T15:11:17Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Snow White and the Seven Dwarfs', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 1, '2021-01-12T21:07:36Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Point of Order', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 1, '2021-01-29T14:09:54Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Sekirei', 'In congue. Etiam justo. Etiam pretium iaculis justo.', 1, '2021-08-05T13:34:59Z');
// insert into post (title, text, "creatorId", "createdAt") values ('1, 2, 3, Sun (Un, deuz, trois, soleil)', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', 1, '2021-05-03T10:19:29Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Vassilisa the Beautiful (Vasilisa prekrasnaya)', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 1, '2021-06-29T14:41:54Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Flower Drum Song', 'In congue. Etiam justo. Etiam pretium iaculis justo.', 1, '2021-06-23T00:48:24Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Eye for an Eye, An (Silmä silmästä)', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 1, '2021-09-29T07:48:57Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Rise & Fall of ECW, The', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 1, '2021-03-02T09:05:00Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Demoted', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 1, '2021-07-20T19:15:03Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Jönssonligan - Den perfekta stöten', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 1, '2021-03-31T18:43:24Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Our Vinyl Weighs a Ton: This Is Stones Throw Records', 'Fusce consequat. Nulla nisl. Nunc nisl.', 1, '2021-04-23T01:22:51Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Hitting Home', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 1, '2021-09-03T23:50:33Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Treasure Hunter, The (Ci ling)', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 1, '2021-09-30T21:10:15Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Ernest in the Army', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 1, '2020-11-18T16:48:12Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Shoes of the Fisherman, The', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 1, '2020-12-03T23:26:57Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Illusionist, The (L''illusionniste)', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.', 1, '2021-05-28T00:04:38Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Mona Lisa Smile', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 1, '2021-05-01T05:02:07Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Maniac', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 1, '2021-04-05T21:47:26Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Scenic Route, The', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 1, '2021-07-11T22:33:15Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Wild Orchid', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 1, '2021-10-25T03:05:23Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Double Solitaire', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 1, '2020-11-30T14:21:27Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Foon', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 1, '2021-02-21T16:41:00Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Neurons to Nirvana', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 1, '2021-10-01T09:15:57Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Deal, The', 'Fusce consequat. Nulla nisl. Nunc nisl.', 1, '2021-06-18T09:54:59Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Amore (L''Amore)', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', 1, '2021-07-15T13:13:01Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Story of My Death', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 1, '2020-11-14T02:35:17Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Matchmaker, The', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 1, '2021-10-20T08:10:54Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Hunchback of Notre Dame, The', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 1, '2020-11-18T20:38:24Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Omar Killed Me (Omar m''a tuer)', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 1, '2021-08-08T18:58:45Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Oliver Twist', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 1, '2020-12-17T09:33:25Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Disraeli', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 1, '2020-11-22T18:13:48Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Nothing to Lose', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 1, '2020-12-14T12:55:21Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Moby Dick', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 1, '2021-01-01T21:45:11Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Inserts', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 1, '2020-12-14T06:35:28Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Ladrón que roba a ladrón', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 1, '2021-03-26T13:35:23Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Space Pirate Captain Harlock', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', 1, '2021-10-05T22:17:42Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Big Bad Mama II', 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.', 1, '2021-02-24T17:37:47Z');
// insert into post (title, text, "creatorId", "createdAt") values ('An Empress and the Warriors', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 1, '2021-06-29T11:15:23Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Inside: ''Dr. Strangelove or How I Learned to Stop Worrying and Love the Bomb''', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 1, '2021-05-12T22:15:01Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Pinocchio', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', 1, '2021-06-21T13:00:31Z');
// insert into post (title, text, "creatorId", "createdAt") values ('My Life So Far', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 1, '2021-10-24T19:44:28Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Scarlet Pimpernel, The', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 1, '2020-11-14T08:50:36Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Punishment Park', 'Maecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', 1, '2021-04-26T09:10:46Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Mystery Men', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 1, '2021-08-13T08:32:15Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Beautiful People', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', 1, '2021-03-17T05:33:08Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Constant Gardener, The', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 1, '2021-03-27T01:37:01Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Path to War', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 1, '2021-02-12T19:02:33Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Best Worst Movie', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 1, '2020-12-21T00:31:41Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Hundred-Foot Journey, The', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 1, '2020-11-17T13:31:52Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Oscar', 'Fusce consequat. Nulla nisl. Nunc nisl.', 1, '2021-02-16T06:38:30Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Escape Fire: The Fight to Rescue American Healthcare', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 1, '2021-06-01T19:30:17Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Blood Ties', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 1, '2021-04-28T12:59:11Z');
// insert into post (title, text, "creatorId", "createdAt") values ('John Q', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 1, '2021-05-15T13:58:38Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Who''s the Man?', 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', 1, '2020-12-16T20:23:04Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Earth Girls Are Easy', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', 1, '2021-08-29T16:45:42Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Keeping Mum', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 1, '2021-06-01T19:33:54Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Cry-Baby', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 1, '2021-08-27T23:54:42Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Viridiana', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 1, '2021-10-14T00:23:48Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Unknown White Male', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 1, '2021-01-29T01:51:48Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Stranger on the Prowl (Imbarco a mezzanotte)', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 1, '2020-12-08T17:16:37Z');
// insert into post (title, text, "creatorId", "createdAt") values ('In the Land of Women', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 1, '2021-02-12T01:37:31Z');
// insert into post (title, text, "creatorId", "createdAt") values ('In a Dark Place', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 1, '2021-08-24T04:06:33Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Full Speed (À toute vitesse)', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 1, '2021-08-28T04:21:28Z');
// insert into post (title, text, "creatorId", "createdAt") values ('He''s Just Not That Into You', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 1, '2021-07-20T18:05:18Z');
// insert into post (title, text, "creatorId", "createdAt") values ('No Good Deed (a.k.a. The House on Turk Street)', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 1, '2020-12-31T00:49:24Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Rest Stop', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', 1, '2021-01-31T20:22:27Z');
// insert into post (title, text, "creatorId", "createdAt") values ('November Man, The', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 1, '2020-12-13T15:47:06Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Moontide', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 1, '2021-02-03T16:22:13Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Hero at Large', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', 1, '2021-01-30T05:39:44Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Menace II Society', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 1, '2021-03-13T07:26:46Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Jazz', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 1, '2021-02-26T08:43:59Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Serbian Film, A (Srpski film)', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 1, '2021-10-03T03:05:47Z');
// insert into post (title, text, "creatorId", "createdAt") values ('B*A*P*S', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 1, '2021-05-14T23:21:40Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Toronto Stories', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 1, '2021-03-03T15:25:16Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Paradise for Three', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 1, '2021-06-15T22:53:07Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Raanjhanaa', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 1, '2021-09-10T12:35:55Z');
// insert into post (title, text, "creatorId", "createdAt") values ('From the Life of the Marionettes (Aus dem Leben der Marionetten) ', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 1, '2021-05-14T20:12:02Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Threads', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 1, '2021-06-12T06:41:06Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Panic', 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.', 1, '2021-04-08T16:58:35Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Royal Scandal, The', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 1, '2021-04-27T02:24:23Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Player''s Club, The', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 1, '2021-05-09T07:33:29Z');
// insert into post (title, text, "creatorId", "createdAt") values ('The Four Feathers', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 1, '2021-04-09T00:18:33Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Song of the Little Road (Pather Panchali)', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 1, '2020-12-05T02:19:37Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Funny Ha Ha', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 1, '2021-08-27T11:02:18Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Kansas', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.', 1, '2021-10-18T11:08:28Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Blood Wedding (Bodas de sangre)', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 1, '2021-09-24T18:31:09Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Conquest, The (La conquête)', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 1, '2021-07-22T15:58:24Z');
// insert into post (title, text, "creatorId", "createdAt") values ('12 Rounds', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 1, '2021-08-22T17:03:07Z');
// insert into post (title, text, "creatorId", "createdAt") values ('ABCs of Death, The', 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 1, '2021-07-07T01:58:51Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Story of Vernon and Irene Castle, The', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 1, '2021-06-10T22:29:39Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Vegas Vacation (National Lampoon''s Las Vegas Vacation)', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 1, '2020-12-11T09:29:51Z');
// insert into post (title, text, "creatorId", "createdAt") values ('All the Invisible Children', 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 1, '2021-03-06T09:58:18Z');
// insert into post (title, text, "creatorId", "createdAt") values ('North Face (Nordwand)', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 1, '2021-08-10T07:09:03Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Beaufort', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 1, '2021-08-09T22:52:40Z');
// insert into post (title, text, "creatorId", "createdAt") values ('Mirror, The (Ayneh)', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 1, '2021-04-08T03:22:14Z');
// insert into post (title, text, "creatorId", "createdAt") values ('16 to Life', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 1, '2021-07-30T00:24:01Z');
// insert into post (title, text, "creatorId", "createdAt") values ('2 + 2 (Dos más dos)', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', 1, '2021-05-15T05:52:39Z');

//         `);
    }

    public async down(_: QueryRunner): Promise<void> {
    }

}
